Get the tracking correct for taskid=0

diff --git a/bin/apply_cal.tmpl b/bin/apply_cal.tmpl
--- a/bin/apply_cal.tmpl
+++ b/bin/apply_cal.tmpl
@@ -6,12 +6,10 @@
 #SBATCH --time=06:00:00
 #SBATCH --nodes=1
 
-
 function test_fail {
 if [[ $1 != 0 ]]
 then
-    cd ${base}
-    python bin/track_task.py fail --jobid=${SLURM_JOBID} --finish_time=`date +%s`
+    track_task.py fail --jobid=${SLURM_JOBID} --taskid=0 --finish_time=`date +%s`
     exit $1
 fi
 }
@@ -21,8 +19,7 @@ base=BASEDIR
 obsnum=OBSNUM
 
 # apply calibration
-cd ${base}
-python bin/track_task.py start --jobid=${SLURM_JOBID} --start_time=`date +%s`
+track_task.py start --jobid=${SLURM_JOBID} --taskid=0 --start_time=`date +%s`
 
 cd ${base}/${obsnum}
 
@@ -30,8 +27,15 @@ cd ${base}/${obsnum}
 calfile=($( ls -1t ${base}/${calid}/${calid}_*_solutions.bin))
 calfile=${calfile[0]}
 
+if [[ $? != 0 ]]
+then
+    echo "Could not find calibrator file"
+    echo "looked for latest of: ${base}/${calid}/${calid}*solutions*.bin"
+    track_task.py fail --jobid=${SLURM_JOBID} --taskid=0 --finish_time=`date +%s`
+    exit 1
+fi
+
 applysolutions ${obsnum}.ms ${calfile}
 test_fail $?
 
-cd ${base}
-python bin/track_task.py finish --jobid=${SLURM_JOBID} --finish_time=`date +%s`
+track_task.py finish --jobid=${SLURM_JOBID} --taskid=0 --finish_time=`date +%s`
