added ability to zip measurement files in place

diff --git a/templates/darchive.tmpl b/templates/darchive.tmpl
--- a/templates/darchive.tmpl
+++ b/templates/darchive.tmpl
@@ -36,15 +36,23 @@ track_task.py start --jobid="${jobid}" --taskid="${taskid}" --start_time="$(date
 base=BASEDIR
 
 datadir="${base}/${obsnum}"
-cd "${datadir}" || exit 1
+cd "${datadir}" || (echo "Could not cd to ${datadir}" && exit 1)
 
 MS="${obsnum}.ms"
 if [[ ! -z "${GXSTAGE}" ]] && [[ -d "${GXSTAGE}" ]]
 then
-    echo "Copying and zipping ${MS} to staging area ${GXSTAGE}"
-    zip -r "${GXSTAGE}/${MS}.zip.tmp" "${MS}" && \
-    mv "${GXSTAGE}/${MS}.zip.tmp" "${GXSTAGE}/${MS}.zip"
-    chmod 775 "${GXSTAGE}/${MS}.zip" # Ensure rsync can --remove-source-files
+    if [ -f "${MS}.zip" ]
+    then
+        echo "Copying zipped MS to staging area ${GXSTAGE}"
+        cp "${MS}.zip" "${GXSTAGE}/${MS}.zip.tmp" && \
+        mv "${MS}.zip.tmp" "${MS}.zip"
+        chmod 755 "${GXSTAGE}/${MS}.zip"
+    else
+        echo "Copying and zipping ${MS} to staging area ${GXSTAGE}"
+        zip -r "${GXSTAGE}/${MS}.zip.tmp" "${MS}" && \
+        mv "${GXSTAGE}/${MS}.zip.tmp" "${GXSTAGE}/${MS}.zip"
+        chmod 775 "${GXSTAGE}/${MS}.zip" # Ensure rsync can --remove-source-files
+    fi
 fi
 
 subchans="0000 0001 0002 0003 MFS"
